logging.level.com.valtech.advertising: DEBUG

server:
  port: 9000
  contextPath: /ms-advertise

spring:
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017/advertising

baseUrl: http://localhost:%s/v1/rentals

message:
  listSize: Advertising list size doesn't match
  notThrown: Did not throw
  responseStatus: Response status doesn't match